import { Theme } from "@radix-ui/themes";
import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import "@radix-ui/themes/styles.css";
import MobileNav from "../../components/MobileNav";
import DesktopNav from "@/components/DesktopNav";
import ThemeObserver from "@/components/ThemeObserver";

const geistSans = localFont({
  src: "../fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "../fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  modal
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
      className={`${geistSans.variable} ${geistMono.variable} antialiased `}>
        <Theme>
        {modal}
          <div className="flex min-h-screen dark:bg-gray-950 dark:text-gray-300">
           <DesktopNav/>
            <div className="pb-24 pt-4 lg:pb-4 lg:px-8  px-4  w-full ">
              {children}
             </div>
          </div>
          <MobileNav />
        </Theme>
        <ThemeObserver/>
      </body>
    </html>
  );
}
